<a href="https://colab.research.google.com/github/roopkanwalvirk97/Weather-data-analysis/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Weather data analysis Project using Python**

#Import the Library

In [1]:
import pandas as pd

# Importing the dataset

In [15]:
df = pd.read_csv('Weather Data.csv')

In [16]:
df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

#.head()
Pandas head() method is used to return top n (5 by default) rows of a data frame or series.

In [17]:
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

#.tail()
The tail() method returns a specified number of last rows.

In [18]:
df.tail()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

#.shape
Return a tuple representing the dimensionality of the DataFrame.

In [19]:
df.shape

(8784, 8)

#.index
Return the index information of the DataFrame.

In [20]:
df.index

RangeIndex(start=0, stop=8784, step=1)

#.columns
This attribute return the column labels of the given Dataframe.

In [21]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

#.dtypes
This returns a Series with the data type of each column.

In [22]:
df.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

#.unique()
To get unique values from a specific column.

In [23]:
df['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

#nunique()
 It is used to get a count of unique values from whole dataframe.

In [24]:
df.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

#.count()
Count the number of (not NULL) values in each column.

In [25]:
df.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

#.info()
This method prints information about the DataFrame.

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

#.describe()
 This method returns description of the data in the DataFrame. It is used to view some basic statistical details like percentile, mean, std, etc. of a data frame or a series of numeric values.

In [27]:
df.describe()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000

#.value_counts
Return a Series containing counts of unique values.

In [28]:
df["Weather"].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: Weather, dtype: int64

# To Find all the unique values in "Visibility_km" in the dataset

In [29]:
df.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [30]:
df['Visibility_km'].nunique()

24

In [31]:
df['Visibility_km'].unique()

array([ 8. ,  4. ,  4.8,  6.4,  1.2, 12.9, 16.1, 25. , 19.3, 24.1,  9.7,
       11.3, 48.3,  3.2,  2.8,  2.4,  2. ,  0.8,  0.6,  1. ,  1.6,  3.6,
        0.2,  0.4])

# To find the number of times when the weather is "Mostly Cloudy"

In [32]:
df.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: Weather, dtype: int64

In [33]:
df[df.Weather == "Mostly Cloudy"]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
16,1/1/2012 16:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
28,1/2/2012 4:00,2.9,-2.3,69,32,25.0,99.26,Mostly Cloudy
29,1/2/2012 5:00,2.6,-2.3,70,32,25.0,99.21,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8743,12/30/2012 7:00,-9.9,-13.2,77,19,25.0,100.48,Mostly Cloudy
8748,12/30/2012 12:00,-12.2,-15.7,75,26,48.3,100.91,Mostly Cloudy
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8763,12/31/2012 3:00,-11.8,-14.4,81,6,25.0,101.42,Mostly Cloudy

In [34]:
df.groupby('Weather').get_group('Mostly Cloudy')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
16,1/1/2012 16:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
28,1/2/2012 4:00,2.9,-2.3,69,32,25.0,99.26,Mostly Cloudy
29,1/2/2012 5:00,2.6,-2.3,70,32,25.0,99.21,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8743,12/30/2012 7:00,-9.9,-13.2,77,19,25.0,100.48,Mostly Cloudy
8748,12/30/2012 12:00,-12.2,-15.7,75,26,48.3,100.91,Mostly Cloudy
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8763,12/31/2012 3:00,-11.8,-14.4,81,6,25.0,101.42,Mostly Cloudy

# To find the number of times when the "relRel Hum" was exactly 85%

In [35]:
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [36]:
df[df['Rel Hum_%'] == 85]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
7,1/1/2012 7:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,1/1/2012 8:00,-1.4,-3.6,85,9,8.0,101.23,Fog
15,1/1/2012 15:00,1.8,-0.4,85,22,6.4,100.07,Fog
21,1/1/2012 21:00,4.0,1.7,85,20,25.0,99.39,Cloudy
127,1/6/2012 7:00,-14.4,-16.3,85,22,2.4,100.52,Snow
...,...,...,...,...,...,...,...,...
8733,12/29/2012 21:00,-9.8,-11.8,85,24,8.0,100.24,"Snow,Fog"
8735,12/29/2012 23:00,-10.0,-12.0,85,20,6.4,100.19,"Snow,Fog"
8766,12/31/2012 6:00,-9.7,-11.7,85,4,25.0,101.23,Cloudy
8767,12/31/2012 7:00,-9.3,-11.3,85,0,19.3,101.19,Snow Showers
8777,12/31/2012 17:00,-1.1,-3.3,85,19,9.7,100.30,Snow

# To find the null values in the data

In [38]:
df.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

# To find mean Wind Speed_km/h

In [39]:
df['Wind Speed_km/h'].mean()

14.94546903460838

#To find Standard Deviation of "Visibility_km" in the data

In [40]:
df.Visibility_km.std()

12.622688245171492

#To find the variance of "Press_kPa" in the data

In [41]:
df.Press_kPa.var()

0.7123440111838423

#To find all the instances when "Snow Showers" were recorded

In [43]:
df['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: Weather, dtype: int64

In [44]:
df[df['Weather'] == "Snow Showers"]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
41,1/2/2012 17:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,1/2/2012 20:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,1/2/2012 21:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,1/2/2012 23:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,1/3/2012 0:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
50,1/3/2012 2:00,-10.5,-15.8,65,22,12.9,100.53,Snow Showers
51,1/3/2012 3:00,-11.3,-18.7,54,33,25.0,100.61,Snow Showers
53,1/3/2012 5:00,-12.9,-19.1,60,22,25.0,100.76,Snow Showers
54,1/3/2012 6:00,-13.3,-19.3,61,19,25.0,100.85,Snow Showers
271,1/12/2012 7:00,-7.3,-12.7,65,28,16.1,100.69,Snow Showers
569,1/24/2012 17:00,1.6,-2.8,73,26,24.1,100.88,Snow Showers
570,1/24/2012 18:00,1.5,-2.9,72,22,25.0,100.95,Snow Showers
571,1/24/2012 19:00,1.5,-3.2,71,32,25.0,101.01,Snow Showers
575,1/24/2012 23:00,1.0,-3.4,72,28,25.0,101.16,Snow Showers
620,1/26/2012 20:00,-4.6,-13.0,52,17,25.0,101.15,Snow Showers
649,1/28/2012 1:00,-0.2,-2.9,82,22,25.0,100.34,Snow Showers
770,2/2/2012 2:00,-6.3,-9.6,77,4,16.1,101.45,Snow Showers
771,2/2/2012 3:00,-5.6,-9.1,76,6,25.0,101.52,Snow Showers
772,2/2/2012 4:00,-5.5,-8.8,78,4,16.1,101.59,Snow Showers
773,2/2/2012 5:00,-5.2,-9.5,72,9,16.1,101.62,Snow Showers
774,2/2/2012 6:00,-6.0,-11.8,63,13,25.0,101.63,Snow Showers
891,2/7/2012 3:00,0.8,-5.0,65,19,25.0,100.94,Snow Showers
980,2/10/2012 20:00,-0.2,-5.2,69,15,25.0,100.88,Snow Showers
1285,2/23/2012 13:00,2.1,-2.1,74,20,16.1,99.49,Snow Showers
1533,3/4/2012 21:00,-9.0,-13.7,69,15,25.0,100.18,Snow Showers
1678,3/10/2012 22:00,-2.0,-7.1,68,11,25.0,102.50,Snow Showers
7401,11/4/2012 9:00,2.9,-1.2,74,17,24.1,101.12,Snow Showers
7432,11/5/2012 16:00,1.1,-6.0,59,19,24.1,101.44,Snow Showers
7882,11/24/2012 10:00,1.8,-2.5,73,30,24.1,99.62,Snow Showers
7883,11/24/2012 11:00,1.6,-3.7,68,33,24.1,99.60,Snow Showers
7884,11/24/2012 12:00,1.8,-5.0,61,30,24.1,99.60,Snow Showers
7889,11/24/2012 17:00,-0.6,-5.3,70,37,12.9,99.81,Snow Showers
7890,11/24/2012 18:00,-0.4,-5.5,68,28,25.0,99.85,Snow Showers
7891,11/24/2012 19:00,-0.9,-5.0,74,22,19.3,99.90,Snow Showers
7907,11/25/2012 11:00,-2.9,-9.6,60,35,48.3,100.28,Snow Showers
7982,11/28/2012 14:00,0.7,-1.3,86,19,3.2,101.42,Snow Showers
7983,11/28/2012 15:00,0.0,-0.8,94,15,2.4,101.37,Snow Showers
7984,11/28/2012 16:00,0.6,-0.9,90,20,6.4,101.37,Snow Showers
7987,11/28/2012 19:00,1.0,-0.7,88,22,12.9,101.35,Snow Showers
7988,11/28/2012 20:00,0.9,-0.9,88,20,16.1,101.36,Snow Showers
7989,11/28/2012 21:00,0.4,-1.9,85,24,16.1,101.38,Snow Showers
8010,11/29/2012 18:00,-4.2,-11.8,55,28,25.0,101.78,Snow Showers
8147,12/5/2012 11:00,2.2,-2.5,71,30,24.1,101.17,Snow Showers
8148,12/5/2012 12:00,1.1,-4.8,65,26,24.1,101.23,Snow Showers
8244,12/9/2012 12:00,-1.9,-5.1,79,17,12.9,102.32,Snow Showers
8313,12/12/2012 9:00,-6.1,-9.0,80,4,24.1,102.21,Snow Showers
8314,12/12/2012 10:00,-4.7,-7.6,80,9,24.1,102.20,Snow Showers
8321,12/12/2012 17:00,-3.2,-6.0,81,7,9.7,102.25,Snow Showers
8322,12/12/2012 18:00,-3.6,-5.7,85,7,12.9,102.28,Snow Showers
8324,12/12/2012 20:00,-4.4,-6.4,86,7,16.1,102.36,Snow Showers
8325,12/12/2012 21:00,-3.9,-5.9,86,6,16.1,102.37,Snow Showers
8326,12/12/2012 22:00,-3.8,-5.6,87,4,11.3,102.40,Snow Showers
8568,12/23/2012 0:00,-7.8,-11.6,74,32,19.3,100.19,Snow Showers
8569,12/23/2012 1:00,-7.9,-11.8,74,32,25.0,100.27,Snow Showers
8575,12/23/2012 7:00,-8.5,-12.1,75,20,19.3,100.52,Snow Showers
8576,12/23/2012 8:00,-8.7,-12.0,77,20,19.3,100.54,Snow Showers
8583,12/23/2012 15:00,-6.8,-11.1,71,13,24.1,100.34,Snow Showers
8584,12/23/2012 16:00,-7.0,-9.6,82,13,9.7,100.35,Snow Showers
8767,12/31/2012 7:00,-9.3,-11.3,85,0,19.3,101.19,Snow Showers
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers

#To find all the instances when "Wind Speed_km/h" is above 30 and "Visibility_km" is 24.1

In [45]:
df[(df['Wind Speed_km/h'] > 30) & (df['Visibility_km'] == 24.1)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
32,1/2/2012 8:00,1.9,-3.3,68,39,24.1,99.14,Mostly Cloudy
33,1/2/2012 9:00,1.8,-3.7,67,44,24.1,99.14,Mostly Cloudy
34,1/2/2012 10:00,1.5,-4.1,66,43,24.1,99.18,Mostly Cloudy
36,1/2/2012 12:00,1.7,-6.2,56,48,24.1,99.21,Mainly Clear
37,1/2/2012 13:00,1.1,-6.5,57,37,24.1,99.27,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8073,12/2/2012 9:00,5.1,2.6,84,32,24.1,101.34,Cloudy
8150,12/5/2012 14:00,0.8,-6.7,57,35,24.1,101.34,Mostly Cloudy
8410,12/16/2012 10:00,-7.7,-13.8,62,32,24.1,101.80,Cloudy
8411,12/16/2012 11:00,-8.2,-13.9,63,35,24.1,101.71,Snow
8747,12/30/2012 11:00,-11.9,-15.4,75,32,24.1,100.89,Cloudy